//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Solutions.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Customer
    {
        public int Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_City { get; set; }
        public Nullable<int> Pin_Code { get; set; }
    }
}
