//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Solutions.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Order
    {
        public int Order_Id { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Total_Qty { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
    }
}
