//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is rhttp://localhost:62721/Data_Context/m_register.csegenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Solutions.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_register
    {
        public int Customer_id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string email_id { get; set; }
        public string Contact_No { get; set; }
        public string Password { get; set; }
    }
}
