//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Solutions.Data_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db_MicraftEntities : DbContext
    {
        public Db_MicraftEntities()
            : base("name=Db_MicraftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_Customer> m_Customer { get; set; }
        public virtual DbSet<m_Order> m_Order { get; set; }
        public virtual DbSet<m_Product> m_Product { get; set; }
        public virtual DbSet<t_line_order> t_line_order { get; set; }
        public virtual DbSet<t_order> t_order { get; set; }
        public virtual DbSet<m_register> m_register { get; set; }
    
        public virtual ObjectResult<Sp_m_Product_Report_Result> Sp_m_Product_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_m_Product_Report_Result>("Sp_m_Product_Report");
        }
    
        public virtual ObjectResult<Sp_m_Customer_Result> Sp_m_Customer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_m_Customer_Result>("Sp_m_Customer");
        }
    
        public virtual ObjectResult<Sp_m_t_order_Result> Sp_m_t_order()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_m_t_order_Result>("Sp_m_t_order");
        }
    }
}
