//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Solutions.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_line_order
    {
        public int Line_ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductCode { get; set; }
    }
}
