//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Solutions.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_order
    {
        public int Order_id { get; set; }
        public Nullable<decimal> order_amount { get; set; }
        public Nullable<decimal> order_qty { get; set; }
        public string customer_name { get; set; }
        public string customer_address { get; set; }
        public string customer_contact { get; set; }
        public Nullable<decimal> order_rate { get; set; }
        public string attr1 { get; set; }
        public string attr2 { get; set; }
        public string attr3 { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
    }
}
